packages:
  branch_codenames:
    master: trusty-unstable
    production: trusty-stable

jobs:
  default:
    builder: "make"
    base: "quay.io/madebymany/build-bases:trusty"
    build_depends:
      - yasm
      - pkg-config
    packages:
      - type: debian
        name: libav-tools
        version: 4:0.11-3
        target: install
        repos:
          - composed-public
