software_groups: &software
  - "base"
jobs:
  default:
    builder: "make"
    base: "ubuntu:12.04"
    software_groups: *software
    build_depends:
      - yasm
      - pkg-config
    packages:
      - type: debian
        name: libav-tools
        version: 4:0.11-1
        target: install
        repos:
          - mxm-public
